---
# tasks file for ejabberd
  - include_vars: "{{ ansible_os_family }}.yml"
    when: ansible_os_family != 'Debian'

  - include: install_RedHat.yml
    when: ansible_os_family == 'RedHat'

  - include: install_Debian.yml
    when: ansible_os_family == 'Debian'

  - include: service.yml
    
      
