---
####
  - name: install ejabberd
    sudo: yes
    apt:
      name: "{{ ejb_pkg }}"
      update_cache: yes
      state: present
###
  - name: config file
    template:
      src: ejabberd.yml.j2
      dest: /etc/ejabberd/ejabberd.yml
      mode: 0644
    notify: restart ejabberd service

  - name: Make sure ejabberd running
    command: systemctl status ejabberd
    ignore_errors: yes
    changed_when: false
    register: service_ejabberd_status

  - name: Report status of Ejabberd
    fail:
      msg: |
        Service Ejabberd is not running.
        Output of `systemctl status ejabberd`:
        {{ service_ejabberd_status.stdout }}
        {{ service_ejabberd_status.stderr }}
    when: service_ejabberd_status | failed

###
#  - name: create user 
#    action: ejabberd_user username={{ user_admin }} host={{ host_name }} password= {{ user_pass }}
####
  - name: create a user if it does not exists
    ejabberd_user:
      username: "{{ user_admin }}"
      host: "{{ ansible_hostname }}"
      password: "{{ user_pass }}"
